/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.54
 * Generated at: 2026-05-06 04:53:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.time.LocalDate;
import in.ps.studentapp.dto.Courses;
import in.ps.studentapp.dao.CoursesDAOImpl;
import in.ps.studentapp.dao.CoursesDAO;
import in.ps.studentapp.dto.Payment;
import in.ps.studentapp.dto.Student;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class bill_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("in.ps.studentapp.dto.Courses");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("in.ps.studentapp.dao.CoursesDAO");
    _jspx_imports_classes.add("in.ps.studentapp.dto.Payment");
    _jspx_imports_classes.add("in.ps.studentapp.dao.CoursesDAOImpl");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("in.ps.studentapp.dto.Student");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Payment Receipt - LearnSphere</title>\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("<style>\n");
      out.write("    :root {\n");
      out.write("        --sunset-orange: #FF6B35;\n");
      out.write("        --black: #000000;\n");
      out.write("        --white: #FFFFFF;\n");
      out.write("        --gray-light: #F5F5F5;\n");
      out.write("        --gray-medium: #E0E0E0;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .receipt-border {\n");
      out.write("        border: 2px solid var(--black);\n");
      out.write("        border-top: 8px solid var(--black);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .dotted-line {\n");
      out.write("        border-bottom: 2px dashed var(--black);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .success-badge {\n");
      out.write("        background-color: #10B981;\n");
      out.write("        color: var(--white);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .failure-badge {\n");
      out.write("        background-color: #EF4444;\n");
      out.write("        color: var(--white);\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-gray-100 min-h-screen flex items-center justify-center p-4\">\n");
      out.write("    ");

        CoursesDAO cdao = new CoursesDAOImpl();
        Student s = (Student) session.getAttribute("student");
        Payment p = (Payment) request.getAttribute("payment");
        
        if(p == null || s == null) {
            response.sendRedirect("courses.jsp?error=Invalid payment receipt");
            return;
        }
        
        Courses c = cdao.getCourses(p.getCourseId());
        String tax = (String) request.getAttribute("tax");
        
        
        // Calculate values
        double courseFees = c.getFees();
        double taxAmount = Double.parseDouble(tax);
        double totalAmount = p.getAmount();
        
        // Determine status color and icon
        String statusClass = "success".equalsIgnoreCase(p.getStatus()) ? "success-badge" : "failure-badge";
        String statusIcon = "success".equalsIgnoreCase(p.getStatus()) ? "fa-check-circle" : "fa-times-circle";
    
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- Main Receipt Container -->\n");
      out.write("    <div class=\"w-full max-w-md bg-white receipt-border rounded-lg shadow-2xl p-6\">\n");
      out.write("        \n");
      out.write("        <!-- Success/Error Messages -->\n");
      out.write("       \n");
      out.write("        <!-- Header -->\n");
      out.write("        <div class=\"text-center mb-6\">\n");
      out.write("            <div class=\"flex items-center justify-center mb-4\">\n");
      out.write("                <div class=\"bg-black text-white p-2 rounded-lg mr-3\">\n");
      out.write("                    <i class=\"fas fa-graduation-cap text-2xl\"></i>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <h1 class=\"text-2xl font-bold text-black\">ProDhee</h1>\n");
      out.write("                    <p class=\"text-sm text-gray-600\">Education Payment Receipt</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Status Badge -->\n");
      out.write("            <div class=\"inline-flex items-center px-4 py-2 rounded-full ");
      out.print( statusClass );
      out.write(" mb-2\">\n");
      out.write("                <i class=\"fas ");
      out.print( statusIcon );
      out.write(" mr-2\"></i>\n");
      out.write("                <span class=\"font-bold uppercase\">");
      out.print( p.getStatus() );
      out.write("</span>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <p class=\"text-gray-600 text-sm\">Transaction completed on ");
      out.print(LocalDate.now());
      out.write("</p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Receipt Content -->\n");
      out.write("        <div class=\"space-y-6\">\n");
      out.write("            <!-- Transaction ID -->\n");
      out.write("            <div class=\"bg-gray-50 p-4 rounded-lg\">\n");
      out.write("                <div class=\"text-center\">\n");
      out.write("                    <p class=\"text-sm text-gray-600 mb-1\">Transaction ID</p>\n");
      out.write("                    <p class=\"font-mono text-lg font-bold text-black tracking-wider\">");
      out.print( p.getTransactionId() );
      out.write("</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Course Details -->\n");
      out.write("            <div>\n");
      out.write("                <h2 class=\"text-lg font-bold text-black mb-3 pb-2 border-b border-gray-200\">Course Details</h2>\n");
      out.write("                <div class=\"space-y-3\">\n");
      out.write("                    <div class=\"flex justify-between\">\n");
      out.write("                        <span class=\"text-gray-600\">Course Name</span>\n");
      out.write("                        <span class=\"font-medium text-black\">");
      out.print( c.getCourseName() );
      out.write("</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"flex justify-between\">\n");
      out.write("                        <span class=\"text-gray-600\">Duration</span>\n");
      out.write("                        <span class=\"font-medium text-black\">");
      out.print( c.getMonths());
      out.write(" months</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Student Details -->\n");
      out.write("            <div>\n");
      out.write("                <h2 class=\"text-lg font-bold text-black mb-3 pb-2 border-b border-gray-200\">Student Information</h2>\n");
      out.write("                <div class=\"space-y-3\">\n");
      out.write("                    <div class=\"flex justify-between\">\n");
      out.write("                        <span class=\"text-gray-600\">Student Name</span>\n");
      out.write("                        <span class=\"font-medium text-black\">");
      out.print( s.getName() );
      out.write("</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"flex justify-between\">\n");
      out.write("                        <span class=\"text-gray-600\">Phone Number</span>\n");
      out.write("                        <span class=\"font-medium text-black\">");
      out.print( s.getPhone() );
      out.write("</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Payment Breakdown -->\n");
      out.write("            <div>\n");
      out.write("                <h2 class=\"text-lg font-bold text-black mb-3 pb-2 border-b border-gray-200\">Payment Summary</h2>\n");
      out.write("                <div class=\"space-y-3\">\n");
      out.write("                    <div class=\"flex justify-between\">\n");
      out.write("                        <span class=\"text-gray-600\">Course Fees</span>\n");
      out.write("                        <span class=\"font-medium\">&#8733;");
      out.print(c.getFees());
      out.write("0/-</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"flex justify-between\">\n");
      out.write("                        <span class=\"text-gray-600\">GST (18%)</span>\n");
      out.write("                        <span class=\"font-medium\">&#8733;");
      out.print(tax);
      out.write("0/-</span>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <!-- Dotted Line Separator -->\n");
      out.write("                    <div class=\"dotted-line pt-2\"></div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"flex justify-between pt-2\">\n");
      out.write("                        <span class=\"text-lg font-bold text-black\">Total Amount</span>\n");
      out.write("                        <span class=\"text-xl font-bold text-black\">&#8733;");
      out.print(p.getAmount());
      out.write("0/-</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Payment Method -->\n");
      out.write("            <div class=\"bg-gray-50 p-4 rounded-lg\">\n");
      out.write("                <div class=\"flex items-center justify-between\">\n");
      out.write("                    <div>\n");
      out.write("                        <p class=\"text-sm text-gray-600 mb-1\">Payment Method</p>\n");
      out.write("                        <p class=\"font-medium text-black\">\n");
      out.write("                            ");
 
                                String method = p.getMethod();
                                String methodIcon = "";
                                
                                switch(method.toLowerCase()) {
                                    case "card":
                                        methodIcon = "fa-credit-card";
                                        method = "Credit/Debit Card";
                                        break;
                                    case "upi":
                                        methodIcon = "fa-mobile-alt";
                                        method = "UPI Payment";
                                        break;
                                    case "netbanking":
                                        methodIcon = "fa-university";
                                        method = "Net Banking";
                                        break;
                                    case "wallet":
                                        methodIcon = "fa-wallet";
                                        method = "Digital Wallet";
                                        break;
                                    default:
                                        methodIcon = "fa-money-bill-wave";
                                }
                            
      out.write("\n");
      out.write("                            <i class=\"fas ");
      out.print( methodIcon );
      out.write(" mr-2\"></i>\n");
      out.write("                            ");
      out.print( method );
      out.write("\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"text-right\">\n");
      out.write("                        <p class=\"text-sm text-gray-600 mb-1\">Amount Paid</p>\n");
      out.write("                        <p class=\"text-xl font-bold text-black\">&#8733;");
      out.print(p.getAmount());
      out.write("0/-</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Receipt Footer -->\n");
      out.write("            <div class=\"text-center pt-4 border-t border-gray-200\">\n");
      out.write("          \n");
      out.write("                <!-- Action Buttons -->\n");
      out.write("                <div class=\"flex space-x-3 mt-6\">\n");
      out.write("                    <a href=\"my-courses.jsp\" \n");
      out.write("                       class=\"flex-1 bg-black text-white font-semibold py-3 rounded-lg text-center hover:bg-gray-800 transition duration-200\">\n");
      out.write("                        <i class=\"fas fa-book mr-2\"></i>\n");
      out.write("                        View Courses\n");
      out.write("                    </a>\n");
      out.write("                    <!-- Print Button (CSS-only) -->\n");
      out.write("                    <button onclick=\"window.print()\" \n");
      out.write("                            class=\"flex-1 border-2 border-black text-black font-semibold py-3 rounded-lg text-center hover:bg-gray-100 transition duration-200\">\n");
      out.write("                        <i class=\"fas fa-print mr-2\"></i>\n");
      out.write("                        Print Receipt\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Note for Print -->\n");
      out.write("                <div class=\"mt-4 p-3 bg-yellow-50 rounded-lg hidden print:block\">\n");
      out.write("                    <p class=\"text-sm text-yellow-800 text-center\">\n");
      out.write("                        <i class=\"fas fa-info-circle mr-2\"></i>\n");
      out.write("                        This is your official payment receipt. Please keep it for your records.\n");
      out.write("                    </p>\n");
      out.write("                    <p class=\"text-xs text-gray-500\">\n");
      out.write("                For any queries, contact: support@learnsphere.com | +1 (555) 123-4567\n");
      out.write("            </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Receipt Footer Note -->\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Print Styles -->\n");
      out.write("    <style>\n");
      out.write("        @media print {\n");
      out.write("            body {\n");
      out.write("                background-color: white;\n");
      out.write("                padding: 0;\n");
      out.write("                margin: 0;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .receipt-border {\n");
      out.write("                border: 2px solid black;\n");
      out.write("                box-shadow: none;\n");
      out.write("                width: 100%;\n");
      out.write("                max-width: 100%;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            button, a {\n");
      out.write("                display: none !important;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .hidden.print\\:block {\n");
      out.write("                display: block !important;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .no-print {\n");
      out.write("                display: none !important;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Ensure proper layout for print */\n");
      out.write("        @page {\n");
      out.write("            margin: 0.5cm;\n");
      out.write("            size: A4 portrait;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
