/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.54
 * Generated at: 2026-05-06 04:51:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import in.ps.studentapp.dto.Courses;
import java.util.ArrayList;
import in.ps.studentapp.dao.CoursesDAOImpl;
import in.ps.studentapp.dao.CoursesDAO;
import in.ps.studentapp.dto.Student;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1778042753527L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1778042753608L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("in.ps.studentapp.dto.Courses");
    _jspx_imports_classes.add("in.ps.studentapp.dao.CoursesDAO");
    _jspx_imports_classes.add("in.ps.studentapp.dao.CoursesDAOImpl");
    _jspx_imports_classes.add("in.ps.studentapp.dto.Student");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Student Courses Portal</title>\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("    <style>\n");
      out.write("       \n");
      out.write("        :root {\n");
      out.write("            --sunset-orange: #FF6B35;\n");
      out.write("            --sunset-orange-light: #FF8E5E;\n");
      out.write("            --sunset-orange-dark: #E55A2B;\n");
      out.write("            --black: #000000;\n");
      out.write("            --white: #FFFFFF;\n");
      out.write("            --gray-light: #F5F5F5;\n");
      out.write("            --gray-medium: #E0E0E0;\n");
      out.write("            --gray-dark: #333333;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .course-card {\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("            border: 1px solid var(--gray-medium);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .course-card:hover {\n");
      out.write("            transform: translateY(-8px);\n");
      out.write("            box-shadow: 0 12px 20px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-link {\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-link.active::after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            bottom: -5px;\n");
      out.write("            left: 0;\n");
      out.write("            right: 0;\n");
      out.write("            height: 3px;\n");
      out.write("            background-color: var(--sunset-orange);\n");
      out.write("            border-radius: 3px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero-gradient {\n");
      out.write("            background: linear-gradient(135deg, #FF6B35 0%, #FF8E5E 50%, #FFB38A 100%);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-primary {\n");
      out.write("            background-color: var(--sunset-orange);\n");
      out.write("            color: var(--white);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background-color: var(--sunset-orange-dark);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-outline {\n");
      out.write("            border: 2px solid var(--sunset-orange);\n");
      out.write("            color: var(--sunset-orange);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-outline:hover {\n");
      out.write("            background-color: var(--sunset-orange);\n");
      out.write("            color: var(--white);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .category-tag {\n");
      out.write("            font-weight: 600;\n");
      out.write("            padding: 4px 12px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            font-size: 0.75rem;\n");
      out.write("            display: inline-block;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("       \n");
      out.write("        \n");
      out.write("        .category-courseName {\n");
      out.write("            background-color: rgba(0, 150, 136, 0.15);\n");
      out.write("            color: #009688;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("     \n");
      out.write("        .level-category {\n");
      out.write("            background-color: rgba(255, 152, 0, 0.15);\n");
      out.write("            color: #FF9800;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("       \n");
      out.write("        \n");
      out.write("       \n");
      out.write("        @keyframes slideDown {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateY(-10px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateY(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .mobile-menu {\n");
      out.write("            animation: slideDown 0.3s ease-out;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("     \n");
      out.write("        .course-filter:target ~ #courses-container .course-card {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #filter-all:target ~ #courses-container .course-card,\n");
      out.write("        #filter-java:target ~ #courses-container .course-card[data-category=\"java\"],\n");
      out.write("        #filter-python:target ~ #courses-container .course-card[data-category=\"python\"],\n");
      out.write("        #filter-mern:target ~ #courses-container .course-card[data-category=\"mern\"],\n");
      out.write("        #filter-devops:target ~ #courses-container .course-card[data-category=\"devops\"] {\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-white text-black\">\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>DevLearn Pro</title>\n");
      out.write("<!-- Tailwind CSS -->\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");

	Student s=(Student)session.getAttribute("student");
    

      out.write("\n");
      out.write("   <!-- Header Section -->\n");
      out.write("    <header class=\"sticky top-0 z-50 bg-white shadow-sm border-b border-gray-200\">\n");
      out.write("        <div class=\"container mx-auto px-4 py-4\">\n");
      out.write("            <div class=\"flex flex-col md:flex-row justify-between items-center\">\n");
      out.write("                <!-- Logo and Brand Name -->\n");
      out.write("                <div class=\"flex items-center space-x-3 mb-4 md:mb-0\">\n");
      out.write("                    <div class=\"bg-black text-white p-2 rounded-lg\">\n");
      out.write("                        <i class=\"fas fa-graduation-cap text-2xl\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <h1 class=\"text-2xl font-bold text-black\">ProDhee</h1>\n");
      out.write("                        <p class=\"text-sm text-gray-600\">Student Courses Portal</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Search option -->\n");
      out.write("<div class=\"w-full md:w-1/3 mb-4 md:mb-0\">\n");
      out.write("    <div class=\"relative\">\n");
      out.write("        <form action=\"search\" method=\"post\" class=\"relative\">\n");
      out.write("            <input \n");
      out.write("                type=\"text\" \n");
      out.write("                name=\"searchQuery\"\n");
      out.write("                placeholder=\"Search courses...\" \n");
      out.write("                class=\"w-full p-3 pl-10 pr-12 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-orange-500\"\n");
      out.write("            >\n");
      out.write("            <i class=\"fas fa-search absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400\"></i>\n");
      out.write("            <button \n");
      out.write("                type=\"submit\" \n");
      out.write("                class=\"absolute right-0 top-0 h-full px-4 bg-orange-500 text-white rounded-r-lg hover:bg-orange-600 transition duration-200 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-offset-2\"\n");
      out.write("            >\n");
      out.write("                Search\n");
      out.write("            </button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("              <!-- User Section -->\n");
      out.write("<div class=\"flex items-center space-x-2 px-4 py-2 rounded-full border border-gray-200 relative group\">\n");
      out.write("    <div class=\"bg-orange-500 text-white p-2 rounded-full cursor-pointer\">\n");
      out.write("        <i class=\"fas fa-user\"></i>\n");
      out.write("    </div>\n");
      out.write("    ");
 if(s != null && s.getId() != 0) { 
      out.write("\n");
      out.write("        <div class=\"cursor-pointer\">\n");
      out.write("            <p class=\"font-medium text-black\">");
      out.print( s.getName() );
      out.write("</p>\n");
      out.write("            <p class=\"text-xs text-gray-600\">Student</p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Dropdown Menu (Hidden by default, shown on hover) -->\n");
      out.write("        <div class=\"absolute top-full right-0 mt-2 w-48 bg-white rounded-lg shadow-xl border border-gray-200 overflow-hidden opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 z-50\">\n");
      out.write("            <div class=\"py-1\">\n");
      out.write("                <!-- User Info Section -->\n");
      out.write("                <div class=\"px-4 py-3 border-b border-gray-100\">\n");
      out.write("                    <p class=\"font-medium text-black\">");
      out.print( s.getName() );
      out.write("</p>\n");
      out.write("                    <p class=\"text-xs text-gray-500\">");
      out.print( s.getMail() );
      out.write("</p>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Menu Items -->\n");
      out.write("                <a href=\"dashboard.jsp\" class=\"flex items-center px-4 py-3 text-gray-700 hover:bg-gray-50 transition duration-150\">\n");
      out.write("                    <i class=\"fas fa-tachometer-alt mr-3 text-gray-500\"></i>\n");
      out.write("                    Dashboard\n");
      out.write("                </a>\n");
      out.write("                \n");
      out.write("                <a href=\"courses?category=all\" class=\"flex items-center px-4 py-3 text-gray-700 hover:bg-gray-50 transition duration-150\">\n");
      out.write("                    <i class=\"fas fa-book mr-3 text-gray-500\"></i>\n");
      out.write("                    My Courses\n");
      out.write("                </a>\n");
      out.write("                \n");
      out.write("                <a href=\"profile.jsp\" class=\"flex items-center px-4 py-3 text-gray-700 hover:bg-gray-50 transition duration-150\">\n");
      out.write("                    <i class=\"fas fa-user-edit mr-3 text-gray-500\"></i>\n");
      out.write("                    Update Account\n");
      out.write("                </a>\n");
      out.write("                \n");
      out.write("                <a href=\"settings.jsp\" class=\"flex items-center px-4 py-3 text-gray-700 hover:bg-gray-50 transition duration-150\">\n");
      out.write("                    <i class=\"fas fa-cog mr-3 text-gray-500\"></i>\n");
      out.write("                    Settings\n");
      out.write("                </a>\n");
      out.write("                \n");
      out.write("                <!-- Logout --> \n");
      out.write("                <form action=\"logout\" method=\"POST\" class=\"border-t border-gray-100\">\n");
      out.write("                    <button type=\"submit\" class=\"w-full text-left flex items-center px-4 py-3 text-red-600 hover:bg-red-50 transition duration-150\">\n");
      out.write("                        <i class=\"fas fa-sign-out-alt mr-3\"></i>\n");
      out.write("                        Logout\n");
      out.write("                    </button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("        <div class=\"flex items-center space-x-4\">\n");
      out.write("            <a href=\"login.jsp\" class=\"text-orange-500 font-medium hover:text-orange-600 transition duration-200\">\n");
      out.write("                Login\n");
      out.write("            </a>\n");
      out.write("            <span class=\"text-gray-300\">|</span>\n");
      out.write("            <a href=\"signup.jsp\" class=\"text-black font-medium hover:text-orange-500 transition duration-200\">\n");
      out.write("                Sign Up\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("</div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Navigation -->\n");
      out.write("        \n");
      out.write("    </header>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"bg-black text-white\">\n");
      out.write("            <div class=\"container mx-auto px-4\">\n");
      out.write("                <div class=\"flex flex-col md:flex-row justify-between items-center\">\n");
      out.write("                    <ul class=\"flex flex-wrap justify-center md:justify-start space-x-1 md:space-x-6 py-3\">\n");
      out.write("                        <li><a href=\"index.jsp\" class=\"nav-link active px-3 py-2 rounded-md hover:bg-gray-800 transition duration-200\">Home</a></li>\n");
      out.write("                        <li><a href=\"index.jsp\" class=\"nav-link course-nav px-3 py-2 rounded-md hover:bg-gray-800 transition duration-200\">Services</a></li>\n");
      out.write("                        <li><a href=\"index.jsp\" class=\"nav-link course-nav px-3 py-2 rounded-md hover:bg-gray-800 transition duration-200\">Contact Us</a></li>\n");
      out.write("                        <li><a href=\"index.jsp\" class=\"nav-link course-nav px-3 py-2 rounded-md hover:bg-gray-800 transition duration-200\">About us</a></li>             \n");
      out.write("                    </ul>\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    <div class=\"md:hidden py-2\">\n");
      out.write("                        <label for=\"mobile-menu-toggle\" class=\"text-white cursor-pointer\">\n");
      out.write("                            <i class=\"fas fa-bars text-xl\"></i>\n");
      out.write("                        </label>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Main Content -->\n");
      out.write("    <main class=\"container mx-auto px-4 py-8\">\n");
      out.write("        <!-- Hero/Promotional Section -->\n");
      out.write("        <section class=\"hero-gradient text-white rounded-2xl p-8 mb-12 shadow-lg\">\n");
      out.write("            <div class=\"max-w-2xl\">\n");
      out.write("                <h2 class=\"text-4xl font-bold mb-4\">Master In-Demand Tech Skills</h2>\n");
      out.write("                <p class=\"text-xl mb-6 opacity-95\">Learn from industry experts with hands-on projects. Transform your career with our curated courses designed for today's job market.</p>\n");
      out.write("                <div class=\"flex flex-wrap gap-4\">\n");
      out.write("                    <a href=\"courses?category=all\" class=\"btn-primary font-semibold px-6 py-3 rounded-lg\">Browse All Courses</a>\n");
      out.write("                    <a href=\"#\" class=\"bg-white text-orange-600 font-semibold px-6 py-3 rounded-lg hover:bg-gray-100 transition duration-200\">Free Trial Lesson</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("          <!-- Filter Anchors (Hidden) -->\n");
      out.write("        <div class=\"hidden\">\n");
      out.write("            <div id=\"filter-all\" class=\"course-filter\"></div>\n");
      out.write("            <div id=\"filter-java\" class=\"course-filter\"></div>\n");
      out.write("            <div id=\"filter-python\" class=\"course-filter\"></div>\n");
      out.write("            <div id=\"filter-mern\" class=\"course-filter\"></div>\n");
      out.write("            <div id=\"filter-devops\" class=\"course-filter\"></div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("		\n");
      out.write("\n");
      out.write("      \n");
      out.write("<div id=\"courses-container\" class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8\"> \n");
      out.write("    <!-- Java Course -->\n");
      out.write("    <div class=\"course-card bg-white rounded-xl overflow-hidden\" data-category=\"java\">\n");
      out.write("        <div class=\"p-6\">\n");
      out.write("            <div class=\"flex justify-between items-start mb-4\">\n");
      out.write("                <div class=\"flex flex-wrap gap-2\">\n");
      out.write("                    <span class=\"category-tag category-java\">Java</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"rating-star\">\n");
      out.write("                    <i class=\"fas fa-star\"></i>\n");
      out.write("                    <span class=\"font-bold ml-1 text-black\">4.8</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"flex items-center mb-3\">\n");
      out.write("                <div class=\"bg-gray-100 p-3 rounded-lg mr-3\">\n");
      out.write("                    <i class=\"fas fa-coffee text-orange-500 text-xl\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3 class=\"text-lg font-bold text-black\">Java Programming</h3>\n");
      out.write("            </div>\n");
      out.write("            <p class=\"text-gray-700 mb-4 text-sm\">Master Java fundamentals and build applications</p>\n");
      out.write("            <div class=\"flex items-center justify-between text-sm\">\n");
      out.write("                <div class=\"text-gray-600\">\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Python Course Example -->\n");
      out.write("    <div class=\"course-card bg-white rounded-xl overflow-hidden\" data-category=\"python\">\n");
      out.write("        <div class=\"p-6\">\n");
      out.write("            <div class=\"flex justify-between items-start mb-4\">\n");
      out.write("                <div class=\"flex flex-wrap gap-2\">\n");
      out.write("                    <span class=\"category-tag category-python\">Python</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"rating-star\">\n");
      out.write("                    <i class=\"fas fa-star\"></i>\n");
      out.write("                    <span class=\"font-bold ml-1 text-black\">4.7</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"flex items-center mb-3\">\n");
      out.write("                <div class=\"bg-gray-100 p-3 rounded-lg mr-3\">\n");
      out.write("                    <i class=\"fab fa-python text-green-500 text-xl\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3 class=\"text-lg font-bold text-black\">Python Data Science</h3>\n");
      out.write("            </div>\n");
      out.write("            <p class=\"text-gray-700 mb-4 text-sm\">Learn data analysis and visualization with Python</p>\n");
      out.write("            <div class=\"flex items-center justify-between text-sm\">\n");
      out.write("                <div class=\"text-gray-600\">\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- MERN Course Example -->\n");
      out.write("    <div class=\"course-card bg-white rounded-xl overflow-hidden\" data-category=\"mern\">\n");
      out.write("        <div class=\"p-6\">\n");
      out.write("            <div class=\"flex justify-between items-start mb-4\">\n");
      out.write("                <div class=\"flex flex-wrap gap-2\">\n");
      out.write("                    <span class=\"category-tag category-mern\">MERN</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"rating-star\">\n");
      out.write("                    <i class=\"fas fa-star\"></i>\n");
      out.write("                    <span class=\"font-bold ml-1 text-black\">4.8</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"flex items-center mb-3\">\n");
      out.write("                <div class=\"bg-gray-100 p-3 rounded-lg mr-3\">\n");
      out.write("                    <i class=\"fab fa-react text-blue-500 text-xl\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3 class=\"text-lg font-bold text-black\">MERN Stack</h3>\n");
      out.write("            </div>\n");
      out.write("            <p class=\"text-gray-700 mb-4 text-sm\">Full stack development with MongoDB, Express, React, Node</p>\n");
      out.write("            <div class=\"flex items-center justify-between text-sm\">\n");
      out.write("                <div class=\"text-gray-600\">\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- DevOps Course Example -->\n");
      out.write("    <div class=\"course-card bg-white rounded-xl overflow-hidden\" data-category=\"devops\">\n");
      out.write("        <div class=\"p-6\">\n");
      out.write("            <div class=\"flex justify-between items-start mb-4\">\n");
      out.write("                <div class=\"flex flex-wrap gap-2\">\n");
      out.write("                    <span class=\"category-tag category-devops\">DevOps</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"rating-star\">\n");
      out.write("                    <i class=\"fas fa-star\"></i>\n");
      out.write("                    <span class=\"font-bold ml-1 text-black\">4.9</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"flex items-center mb-3\">\n");
      out.write("                <div class=\"bg-gray-100 p-3 rounded-lg mr-3\">\n");
      out.write("                    <i class=\"fab fa-docker text-blue-400 text-xl\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3 class=\"text-lg font-bold text-black\">DevOps & CI/CD</h3>\n");
      out.write("            </div>\n");
      out.write("            <p class=\"text-gray-700 mb-4 text-sm\">Master DevOps practices and pipeline automation</p>\n");
      out.write("            <div class=\"flex items-center justify-between text-sm\">\n");
      out.write("                <div class=\"text-gray-600\">\n");
      out.write("                   \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- JavaScript Course Example -->\n");
      out.write("    <div class=\"course-card bg-white rounded-xl overflow-hidden\" data-category=\"javascript\">\n");
      out.write("        <div class=\"p-6\">\n");
      out.write("            <div class=\"flex justify-between items-start mb-4\">\n");
      out.write("                <div class=\"flex flex-wrap gap-2\">\n");
      out.write("                    <span class=\"category-tag category-java\">JavaScript</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"rating-star\">\n");
      out.write("                    <i class=\"fas fa-star\"></i>\n");
      out.write("                    <span class=\"font-bold ml-1 text-black\">4.6</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"flex items-center mb-3\">\n");
      out.write("                <div class=\"bg-gray-100 p-3 rounded-lg mr-3\">\n");
      out.write("                    <i class=\"fab fa-js-square text-yellow-500 text-xl\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3 class=\"text-lg font-bold text-black\">Modern JavaScript</h3>\n");
      out.write("            </div>\n");
      out.write("            <p class=\"text-gray-700 mb-4 text-sm\">Learn ES6+ features and modern web development</p>\n");
      out.write("            <div class=\"flex items-center justify-between text-sm\">\n");
      out.write("                <div class=\"text-gray-600\">\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Cloud Course Example -->\n");
      out.write("    <div class=\"course-card bg-white rounded-xl overflow-hidden\" data-category=\"cloud\">\n");
      out.write("        <div class=\"p-6\">\n");
      out.write("            <div class=\"flex justify-between items-start mb-4\">\n");
      out.write("                <div class=\"flex flex-wrap gap-2\">\n");
      out.write("                    <span class=\"category-tag category-devops\">Cloud</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"rating-star\">\n");
      out.write("                    <i class=\"fas fa-star\"></i>\n");
      out.write("                    <span class=\"font-bold ml-1 text-black\">4.7</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"flex items-center mb-3\">\n");
      out.write("                <div class=\"bg-gray-100 p-3 rounded-lg mr-3\">\n");
      out.write("                    <i class=\"fas fa-cloud text-blue-300 text-xl\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3 class=\"text-lg font-bold text-black\">Cloud Computing</h3>\n");
      out.write("            </div>\n");
      out.write("            <p class=\"text-gray-700 mb-4 text-sm\">Learn AWS, Azure and cloud infrastructure</p>\n");
      out.write("            <div class=\"flex items-center justify-between text-sm\">\n");
      out.write("                <div class=\"text-gray-600\">\n");
      out.write("                    \n");
      out.write("                   \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    ");
 // } // End of for loop in JSP 
      out.write("\n");
      out.write("</div>\n");
      out.write("           \n");
      out.write("        <!-- Call to Action Section -->\n");
      out.write("        <section class=\"mt-16 mb-12 p-8 bg-gray-50 rounded-2xl border border-gray-200\">\n");
      out.write("            <div class=\"text-center max-w-3xl mx-auto\">\n");
      out.write("                <h2 class=\"text-3xl font-bold text-black mb-4\">Ready to Start Your Learning Journey?</h2>\n");
      out.write("                <p class=\"text-gray-700 mb-6 text-lg\">Join thousands of students who have transformed their careers with our expert-led courses. No prior experience needed for beginner courses.</p>\n");
      out.write("                <div class=\"flex flex-wrap justify-center gap-4\">\n");
      out.write("                    <a href=\"courses.jsp\" class=\"btn-primary font-semibold px-8 py-3 rounded-lg text-lg\">Explore All Courses</a>\n");
      out.write("                    <a href=\"#\" class=\"btn-outline font-semibold px-8 py-3 rounded-lg text-lg\">Contact an Advisor</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("   ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style>\n");
      out.write("        /* Sunset Orange Color Palette */\n");
      out.write("        :root {\n");
      out.write("            --sunset-orange: #FF6B35;\n");
      out.write("            --sunset-orange-light: #FF8E5E;\n");
      out.write("            --sunset-orange-dark: #E55A2B;\n");
      out.write("            --black: #000000;\n");
      out.write("            --white: #FFFFFF;\n");
      out.write("            --gray-light: #F5F5F5;\n");
      out.write("            --gray-medium: #E0E0E0;\n");
      out.write("            --gray-dark: #333333;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .course-card {\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("            border: 1px solid var(--gray-medium);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .course-card:hover {\n");
      out.write("            transform: translateY(-8px);\n");
      out.write("            box-shadow: 0 12px 20px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-link {\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-link.active::after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            bottom: -5px;\n");
      out.write("            left: 0;\n");
      out.write("            right: 0;\n");
      out.write("            height: 3px;\n");
      out.write("            background-color: var(--sunset-orange);\n");
      out.write("            border-radius: 3px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero-gradient {\n");
      out.write("            background: linear-gradient(135deg, #FF6B35 0%, #FF8E5E 50%, #FFB38A 100%);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-primary {\n");
      out.write("            background-color: var(--sunset-orange);\n");
      out.write("            color: var(--white);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background-color: var(--sunset-orange-dark);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-outline {\n");
      out.write("            border: 2px solid var(--sunset-orange);\n");
      out.write("            color: var(--sunset-orange);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-outline:hover {\n");
      out.write("            background-color: var(--sunset-orange);\n");
      out.write("            color: var(--white);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .category-tag {\n");
      out.write("            font-weight: 600;\n");
      out.write("            padding: 4px 12px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            font-size: 0.75rem;\n");
      out.write("            display: inline-block;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("       \n");
      out.write("        \n");
      out.write("        .category-courseName {\n");
      out.write("            background-color: rgba(0, 150, 136, 0.15);\n");
      out.write("            color: #009688;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("     \n");
      out.write("        .level-category {\n");
      out.write("            background-color: rgba(255, 152, 0, 0.15);\n");
      out.write("            color: #FF9800;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("       \n");
      out.write("        \n");
      out.write("        /* Mobile menu animation */\n");
      out.write("        @keyframes slideDown {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateY(-10px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateY(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .mobile-menu {\n");
      out.write("            animation: slideDown 0.3s ease-out;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Course filtering with CSS */\n");
      out.write("        .course-filter:target ~ #courses-container .course-card {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #filter-all:target ~ #courses-container .course-card,\n");
      out.write("        #filter-java:target ~ #courses-container .course-card[data-category=\"java\"],\n");
      out.write("        #filter-python:target ~ #courses-container .course-card[data-category=\"python\"],\n");
      out.write("        #filter-mern:target ~ #courses-container .course-card[data-category=\"mern\"],\n");
      out.write("        #filter-devops:target ~ #courses-container .course-card[data-category=\"devops\"] {\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	 <!-- Footer -->\n");
      out.write("    <footer class=\"bg-black text-white pt-10 pb-6\">\n");
      out.write("        <div class=\"container mx-auto px-4\">\n");
      out.write("            <div class=\"grid grid-cols-1 md:grid-cols-4 gap-8 mb-8\">\n");
      out.write("                <div>\n");
      out.write("                    <div class=\"flex items-center space-x-3 mb-4\">\n");
      out.write("                        <div class=\"bg-white text-black p-2 rounded-lg\">\n");
      out.write("                            <i class=\"fas fa-graduation-cap text-2xl\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <h2 class=\"text-xl font-bold\">ProDhee</h2>\n");
      out.write("                            <p class=\"text-sm text-gray-400\">Student Courses Portal</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <p class=\"text-gray-400\">Empowering students with industry-relevant skills through expert-led courses in modern technologies.</p>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div>\n");
      out.write("                    <h3 class=\"text-lg font-bold mb-4 text-white\">Quick Links</h3>\n");
      out.write("                    <ul class=\"space-y-2\">\n");
      out.write("                        <li><a href=\"#filter-all\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">Home</a></li>\n");
      out.write("                        <li><a href=\"#filter-all\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">All Courses</a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">Student Dashboard</a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">Instructors</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div>\n");
      out.write("                    <h3 class=\"text-lg font-bold mb-4 text-white\">Course Categories</h3>\n");
      out.write("                    <ul class=\"space-y-2\">\n");
      out.write("                        <li><a href=\"courses?category=Java\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">Java Programming</a></li>\n");
      out.write("                        <li><a href=\"courses?category=Python\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">Python & Data Science</a></li>\n");
      out.write("                        <li><a href=\"courses?category=Angular%2FReact\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">MEAN and MERN Stacks</a></li>\n");
      out.write("                        <li><a href=\"courses?category=Cloud\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">DevOps & Cloud</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div>\n");
      out.write("                    <h3 class=\"text-lg font-bold mb-4 text-white\">Contact Us</h3>\n");
      out.write("                    <ul class=\"space-y-3\">\n");
      out.write("                        <li class=\"flex items-center space-x-3 text-gray-400\">\n");
      out.write("                            <i class=\"fas fa-envelope text-orange-500\"></i>\n");
      out.write("                            <span>support@prodheetech.com</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"flex items-center space-x-3 text-gray-400\">\n");
      out.write("                            <i class=\"fas fa-phone text-orange-500\"></i>\n");
      out.write("                            <span>+91 9900990099</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"flex items-center space-x-3 text-gray-400\">\n");
      out.write("                            <i class=\"fas fa-map-marker-alt text-orange-500\"></i>\n");
      out.write("                            <span>Yelahanka, Bangalore 560001</span>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"border-t border-gray-800 pt-6 flex flex-col md:flex-row justify-between items-center\">\n");
      out.write("                <p class=\"text-gray-400 text-sm mb-4 md:mb-0\">&copy; 2025 ProDhee. All rights reserved.</p>\n");
      out.write("                <div class=\"flex space-x-4\">\n");
      out.write("                    <a href=\"#\" class=\"text-gray-400 hover:text-orange-500 transition duration-200\">\n");
      out.write("                        <i class=\"fab fa-facebook-f text-xl\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"#\" class=\"text-gray-400 hover:text-orange-500 transition duration-200\">\n");
      out.write("                        <i class=\"fab fa-twitter text-xl\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"#\" class=\"text-gray-400 hover:text-orange-500 transition duration-200\">\n");
      out.write("                        <i class=\"fab fa-linkedin-in text-xl\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"#\" class=\"text-gray-400 hover:text-orange-500 transition duration-200\">\n");
      out.write("                        <i class=\"fab fa-instagram text-xl\"></i>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Mobile Menu (Hidden by default) -->\n");
      out.write("    <div id=\"mobile-menu\" class=\"md:hidden hidden fixed inset-0 z-50 bg-black bg-opacity-95 pt-20 mobile-menu\">\n");
      out.write("        <div class=\"container mx-auto px-4\">\n");
      out.write("            <div class=\"flex flex-col space-y-4\">\n");
      out.write("                <a href=\"index.jsp\" class=\"text-white text-xl font-semibold py-4 border-b border-gray-800 hover:text-orange-500\">Home</a>\n");
      out.write("                <a href=\"courses?category=Java\" class=\"text-white text-xl font-semibold py-4 border-b border-gray-800 hover:text-orange-500\">Java Courses</a>\n");
      out.write("                <a href=\"courses?category=Python\" class=\"text-white text-xl font-semibold py-4 border-b border-gray-800 hover:text-orange-500\">Python Courses</a>\n");
      out.write("                <a href=\"courses?category=Angular%2FReact\" class=\"text-white text-xl font-semibold py-4 border-b border-gray-800 hover:text-orange-500\">MERN Stack Courses</a>\n");
      out.write("                <a href=\"courses?category=Cloud\" class=\"text-white text-xl font-semibold py-4 border-b border-gray-800 hover:text-orange-500\">DevOps Courses</a>\n");
      out.write("                <a href=\"courses?category=all\" class=\"text-white text-xl font-semibold py-4 border-b border-gray-800 hover:text-orange-500\">All Courses</a>\n");
      out.write("                \n");
      out.write("                <div class=\"pt-8\">\n");
      out.write("                    <div class=\"flex items-center space-x-3 px-4 py-3 bg-gray-900 rounded-lg\">\n");
      out.write("                        <div class=\"bg-orange-500 text-white p-2 rounded-full\">\n");
      out.write("                            <i class=\"fas fa-user\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <p class=\"font-medium text-white\">John Doe</p>\n");
      out.write("                            <p class=\"text-sm text-gray-400\">Student Account</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"absolute bottom-8 left-0 right-0 px-4\">\n");
      out.write("                <label for=\"mobile-menu-toggle\" class=\"block text-center text-gray-400 hover:text-white cursor-pointer\">\n");
      out.write("                    <i class=\"fas fa-times text-2xl\"></i>\n");
      out.write("                    <span class=\"block mt-2\">Close Menu</span>\n");
      out.write("                </label>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Hidden checkbox for mobile menu toggle -->\n");
      out.write("    <input type=\"checkbox\" id=\"mobile-menu-toggle\" class=\"hidden\">\n");
      out.write("    \n");
      out.write("    <!-- Mobile menu toggle with CSS-only functionality -->\n");
      out.write("    <style>\n");
      out.write("        /* CSS-only mobile menu toggle */\n");
      out.write("        #mobile-menu-toggle:checked ~ #mobile-menu {\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Update course section title based on filter */\n");
      out.write("        #filter-all:target ~ main #course-section-title::after {\n");
      out.write("            content: \"All Courses\";\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #filter-java:target ~ main #course-section-title::after {\n");
      out.write("            content: \"Java Courses\";\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #filter-python:target ~ main #course-section-title::after {\n");
      out.write("            content: \"Python Courses\";\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #filter-mern:target ~ main #course-section-title::after {\n");
      out.write("            content: \"MERN Stack Courses\";\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #filter-devops:target ~ main #course-section-title::after {\n");
      out.write("            content: \"DevOps Courses\";\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Show/hide courses based on filter */\n");
      out.write("        #filter-all:target ~ main #courses-container .course-card {\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #filter-java:target ~ main #courses-container .course-card:not([data-category=\"java\"]) {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #filter-python:target ~ main #courses-container .course-card:not([data-category=\"python\"]) {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #filter-mern:target ~ main #courses-container .course-card:not([data-category=\"mern\"]) {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #filter-devops:target ~ main #courses-container .course-card:not([data-category=\"devops\"]) {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Highlight active nav link */\n");
      out.write("        #filter-all:target ~ header nav a[href=\"#filter-all\"],\n");
      out.write("        #filter-java:target ~ header nav a[href=\"#filter-java\"],\n");
      out.write("        #filter-python:target ~ header nav a[href=\"#filter-python\"],\n");
      out.write("        #filter-mern:target ~ header nav a[href=\"#filter-mern\"],\n");
      out.write("        #filter-devops:target ~ header nav a[href=\"#filter-devops\"] {\n");
      out.write("            background-color: #333;\n");
      out.write("            color: #FF6B35;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
