/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.54
 * Generated at: 2026-05-06 04:52:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Login - LearnSphere</title>\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --sunset-orange: #FF6B35;\n");
      out.write("            --sunset-orange-light: #FF8E5E;\n");
      out.write("            --sunset-orange-dark: #E55A2B;\n");
      out.write("            --black: #000000;\n");
      out.write("            --white: #FFFFFF;\n");
      out.write("            --gray-light: #F5F5F5;\n");
      out.write("            --gray-medium: #E0E0E0;\n");
      out.write("            --gray-dark: #333333;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-primary {\n");
      out.write("            background-color: var(--sunset-orange);\n");
      out.write("            color: var(--white);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background-color: var(--sunset-orange-dark);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .input-focus:focus {\n");
      out.write("            border-color: var(--sunset-orange);\n");
      out.write("            box-shadow: 0 0 0 2px rgba(255, 107, 53, 0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .link-orange {\n");
      out.write("            color: var(--sunset-orange);\n");
      out.write("            transition: color 0.3s ease;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .link-orange:hover {\n");
      out.write("            color: var(--sunset-orange-dark);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .login-bg {\n");
      out.write("            background: linear-gradient(135deg, #FF6B35 0%, #FF8E5E 100%);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* CSS-only password toggle */\n");
      out.write("        #password-toggle:checked ~ #password {\n");
      out.write("            font-family: \"Courier New\", monospace;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #password-toggle:checked ~ #toggle-password-label .fa-eye {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #password-toggle:not(:checked) ~ #toggle-password-label .fa-eye-slash {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-gray-50 min-h-screen flex items-center justify-center p-4 login-bg\">\n");
      out.write("    <!-- Main Login Container -->\n");
      out.write("    <div class=\"flex flex-col md:flex-row w-full max-w-5xl rounded-2xl overflow-hidden shadow-2xl\">\n");
      out.write("        \n");
      out.write("        <!-- Left Side - Brand & Info -->\n");
      out.write("        <div class=\"md:w-2/5 bg-black text-white p-10 flex flex-col justify-between\">\n");
      out.write("            <div>\n");
      out.write("                <div class=\"flex items-center space-x-3 mb-8\">\n");
      out.write("                    <div class=\"bg-white text-black p-3 rounded-lg\">\n");
      out.write("                        <i class=\"fas fa-graduation-cap text-3xl\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <h1 class=\"text-3xl font-bold\">ProDhee</h1>\n");
      out.write("                        <p class=\"text-gray-300\">Student Courses Portal</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"mt-10\">\n");
      out.write("                    <h2 class=\"text-2xl font-bold mb-4\">Welcome Back!</h2>\n");
      out.write("                    <p class=\"text-gray-300 mb-6\">\n");
      out.write("                        Sign in to access your personalized dashboard, continue your learning journey, and explore new courses.\n");
      out.write("                    </p>\n");
      out.write("                    \n");
      out.write("                    <div class=\"space-y-4\">\n");
      out.write("                        <div class=\"flex items-center space-x-3\">\n");
      out.write("                            <div class=\"bg-orange-500 p-2 rounded-full\">\n");
      out.write("                                <i class=\"fas fa-book text-sm\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <span>Access all your enrolled courses</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"flex items-center space-x-3\">\n");
      out.write("                            <div class=\"bg-orange-500 p-2 rounded-full\">\n");
      out.write("                                <i class=\"fas fa-chart-line text-sm\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <span>Track your learning progress</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"flex items-center space-x-3\">\n");
      out.write("                            <div class=\"bg-orange-500 p-2 rounded-full\">\n");
      out.write("                                <i class=\"fas fa-certificate text-sm\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <span>Get certificates upon completion</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"mt-8 pt-6 border-t border-gray-700\">\n");
      out.write("                <p class=\"text-gray-400 text-sm\">\n");
      out.write("                    Not a member yet? \n");
      out.write("                    <a href=\"signup.jsp\" class=\"link-orange font-medium ml-1\">Create an account</a>\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Right Side - Login Form -->\n");
      out.write("        <div class=\"md:w-3/5 bg-white p-10 flex items-center justify-center\">\n");
      out.write("            <div class=\"w-full max-w-md\">\n");
      out.write("                <div class=\"text-center mb-10\">\n");
      out.write("                    <h2 class=\"text-3xl font-bold text-black mb-2\">Sign In to Your Account</h2>\n");
      out.write("                    <p class=\"text-gray-600\">Enter your credentials to access your account</p>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Login Form -->\n");
      out.write("                <form action=\"login\" method=\"POST\" class=\"space-y-6\">\n");
      out.write("                    <!-- Display error message if exists -->\n");
      out.write("                    ");

                        String error =(String)request.getAttribute("error");
                        if(error != null) {
                    
      out.write("\n");
      out.write("                        <div class=\"bg-red-50 border-l-4 border-red-500 p-4 mb-4\">\n");
      out.write("                            <div class=\"flex\">\n");
      out.write("                                <div class=\"flex-shrink-0\">\n");
      out.write("                                    <i class=\"fas fa-exclamation-circle text-red-500\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"ml-3\">\n");
      out.write("                                    <p class=\"text-sm text-red-700\">\n");
      out.write("                                        ");
      out.print( error);
      out.write("\n");
      out.write("                                    </p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                    \n");
      out.write("                    <!-- Success message after registration -->\n");
      out.write("                    ");

                        String success =(String)request.getAttribute("success");
                        if(success!= null) {
                    
      out.write("\n");
      out.write("                        <div class=\"bg-green-50 border-l-4 border-green-500 p-4 mb-4\">\n");
      out.write("                            <div class=\"flex\">\n");
      out.write("                                <div class=\"flex-shrink-0\">\n");
      out.write("                                    <i class=\"fas fa-check-circle text-green-500\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"ml-3\">\n");
      out.write("                                    <p class=\"text-sm text-green-700\">\n");
      out.write("                                        ");
      out.print(success);
      out.write("\n");
      out.write("                                    </p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                    \n");
      out.write("                    <!-- Email Field -->\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"email\" class=\"block text-sm font-medium text-gray-700 mb-2\">\n");
      out.write("                            <i class=\"fas fa-envelope mr-2 text-orange-500\"></i>\n");
      out.write("                            Email Address\n");
      out.write("                        </label>\n");
      out.write("                        <div class=\"relative\">\n");
      out.write("                            <input \n");
      out.write("                                type=\"email\" \n");
      out.write("                                id=\"email\" \n");
      out.write("                                name=\"mail\" \n");
      out.write("                                required\n");
      out.write("                                placeholder=\"Enter your email\"\n");
      out.write("                                class=\"w-full p-4 pl-12 border border-gray-300 rounded-lg input-focus focus:outline-none transition duration-200\"\n");
      out.write("                            >\n");
      out.write("                            <div class=\"absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400\">\n");
      out.write("                                <i class=\"fas fa-user-circle\"></i>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <p class=\"mt-1 text-xs text-gray-500\">Enter your registered email address</p>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <!-- Password Field with CSS-only toggle -->\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"flex justify-between items-center mb-2\">\n");
      out.write("                            <label for=\"password\" class=\"block text-sm font-medium text-gray-700\">\n");
      out.write("                                <i class=\"fas fa-lock mr-2 text-orange-500\"></i>\n");
      out.write("                                Password\n");
      out.write("                            </label>\n");
      out.write("                            <a href=\"forgot.jsp\" class=\"text-sm link-orange font-medium\">\n");
      out.write("                                Forgot Password?\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"relative\">\n");
      out.write("                            <!-- Hidden checkbox for password toggle -->\n");
      out.write("                            <input type=\"checkbox\" id=\"password-toggle\" class=\"hidden\">\n");
      out.write("                            \n");
      out.write("                            <!-- Password input with conditional styling -->\n");
      out.write("                            <input \n");
      out.write("                                type=\"password\" \n");
      out.write("                                id=\"password\" \n");
      out.write("                                name=\"password\" \n");
      out.write("                                required\n");
      out.write("                                placeholder=\"Enter your password\"\n");
      out.write("                                class=\"w-full p-4 pl-12 pr-12 border border-gray-300 rounded-lg input-focus focus:outline-none transition duration-200\"\n");
      out.write("                            >\n");
      out.write("                            <div class=\"absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400\">\n");
      out.write("                                <i class=\"fas fa-key\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- Password toggle label (acts as button) -->\n");
      out.write("                            <label for=\"password-toggle\" id=\"toggle-password-label\" \n");
      out.write("                                   class=\"absolute right-4 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600 cursor-pointer\">\n");
      out.write("                                <i class=\"fas fa-eye\"></i>\n");
      out.write("                                <i class=\"fas fa-eye-slash\"></i>\n");
      out.write("                            </label>\n");
      out.write("                        </div>\n");
      out.write("                        <p class=\"mt-1 text-xs text-gray-500\">Password must be at least 8 characters</p>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <!-- Remember Me & Terms -->\n");
      out.write("                    <div class=\"flex items-center justify-between\">\n");
      out.write("                        <div class=\"flex items-center\">\n");
      out.write("                            <input \n");
      out.write("                                type=\"checkbox\" \n");
      out.write("                                id=\"remember\" \n");
      out.write("                                name=\"remember\"\n");
      out.write("                                class=\"h-4 w-4 text-orange-500 focus:ring-orange-400 border-gray-300 rounded\"\n");
      out.write("                            >\n");
      out.write("                            <label for=\"remember\" class=\"ml-2 block text-sm text-gray-700\">\n");
      out.write("                                Remember me\n");
      out.write("                            </label>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <!-- Submit Button -->\n");
      out.write("                    <div>\n");
      out.write("                        <button \n");
      out.write("                            type=\"submit\" \n");
      out.write("                            class=\"w-full btn-primary font-semibold py-4 rounded-lg text-lg hover:shadow-lg transition duration-300\"\n");
      out.write("                        >\n");
      out.write("                            <i class=\"fas fa-sign-in-alt mr-2\"></i>\n");
      out.write("                            Sign In\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("                \n");
      out.write("               \n");
      out.write("                \n");
      out.write("                <!-- Sign Up Link -->\n");
      out.write("                <div class=\"text-center\">\n");
      out.write("                    <p class=\"text-gray-600\">\n");
      out.write("                        Don't have an account?\n");
      out.write("                        <a href=\"signup.jsp\" class=\"link-orange font-bold ml-1\">Sign up now</a>\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Back to Home -->\n");
      out.write("                <div class=\"text-center mt-6\">\n");
      out.write("                    <a href=\"index.jsp\" class=\"text-gray-500 hover:text-black transition duration-200\">\n");
      out.write("                        <i class=\"fas fa-arrow-left mr-2\"></i>\n");
      out.write("                        Back to home page\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
