/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.54
 * Generated at: 2026-05-06 04:53:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.time.LocalDateTime;
import in.ps.studentapp.dto.Student;
import in.ps.studentapp.dao.CoursesDAOImpl;
import in.ps.studentapp.dao.CoursesDAO;
import in.ps.studentapp.dto.Courses;
import java.util.Date;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1778042753527L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("in.ps.studentapp.dto.Courses");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("in.ps.studentapp.dao.CoursesDAO");
    _jspx_imports_classes.add("java.time.LocalDateTime");
    _jspx_imports_classes.add("in.ps.studentapp.dao.CoursesDAOImpl");
    _jspx_imports_classes.add("in.ps.studentapp.dto.Student");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Payment - ProDhee</title>\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("<style>\n");
      out.write("    :root {\n");
      out.write("        --sunset-orange: #FF6B35;\n");
      out.write("        --sunset-orange-light: #FF8E5E;\n");
      out.write("        --sunset-orange-dark: #E55A2B;\n");
      out.write("        --black: #000000;\n");
      out.write("        --white: #FFFFFF;\n");
      out.write("        --gray-light: #F5F5F5;\n");
      out.write("        --gray-medium: #E0E0E0;\n");
      out.write("        --gray-dark: #333333;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .btn-primary {\n");
      out.write("        background-color: var(--sunset-orange);\n");
      out.write("        color: var(--white);\n");
      out.write("        transition: all 0.3s ease;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .btn-primary:hover {\n");
      out.write("        background-color: var(--sunset-orange-dark);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .btn-outline {\n");
      out.write("        border: 2px solid var(--sunset-orange);\n");
      out.write("        color: var(--sunset-orange);\n");
      out.write("        transition: all 0.3s ease;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .btn-outline:hover {\n");
      out.write("        background-color: var(--sunset-orange);\n");
      out.write("        color: var(--white);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .link-orange {\n");
      out.write("        color: var(--sunset-orange);\n");
      out.write("        transition: color 0.3s ease;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .link-orange:hover {\n");
      out.write("        color: var(--sunset-orange-dark);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .payment-card {\n");
      out.write("        box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);\n");
      out.write("        border: 1px solid var(--gray-medium);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .payment-option {\n");
      out.write("        border: 2px solid transparent;\n");
      out.write("        transition: all 0.3s ease;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .payment-option:hover {\n");
      out.write("        border-color: var(--sunset-orange);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    /* Payment option selection */\n");
      out.write("    .payment-method:checked + label {\n");
      out.write("        border-color: var(--sunset-orange);\n");
      out.write("        background-color: rgba(255, 107, 53, 0.05);\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-gray-50 min-h-screen\">\n");
      out.write("    <!-- Header -->\n");
      out.write("    <header class=\"bg-white shadow-sm\">\n");
      out.write("        <div class=\"container mx-auto px-4 py-4\">\n");
      out.write("            <div class=\"flex items-center justify-between\">\n");
      out.write("                <!-- Logo -->\n");
      out.write("                <div class=\"flex items-center space-x-3\">\n");
      out.write("                    <div class=\"bg-black text-white p-2 rounded-lg\">\n");
      out.write("                        <i class=\"fas fa-graduation-cap text-2xl\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <h1 class=\"text-2xl font-bold text-black\">ProDhee</h1>\n");
      out.write("                        <p class=\"text-sm text-gray-600\">Student Courses Portal</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- User Info -->\n");
      out.write("                <div class=\"flex items-center space-x-4\">\n");
      out.write("                    <a href=\"courses?category=all\" class=\"text-gray-700 hover:text-orange-500 transition duration-200\">\n");
      out.write("                        <i class=\"fas fa-arrow-left mr-2\"></i>\n");
      out.write("                        Back to Courses\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    ");

    // Get session and course details
    Student s = (Student) session.getAttribute("student");
    String cId = request.getParameter("courseId");
    
    // Check if user is logged in
    if(s == null || s.getId() == 0) {
        response.sendRedirect("login.jsp?error=Please login to make payment");
        return;
    }
    
    // Check if courseId is provided
    if(cId == null || cId.isEmpty()) {
        response.sendRedirect("courses.jsp?error=Invalid course selection");
        return;
    }
    
    Integer courseId = Integer.parseInt(cId);
    CoursesDAO cdao = new CoursesDAOImpl();
    Courses c = cdao.getCourses(courseId);
    
    // Check if course exists
    if(c == null) {
        response.sendRedirect("courses.jsp?error=Course not found");
        return;
    }
    
   
    
    // Calculate tax (18% GST)
    double courseFees = c.getFees();
    double tax = courseFees * 0.18;
    double totalAmount = courseFees + tax;
    
    
      out.write("\n");
      out.write("    \n");
      out.write("    <main class=\"container mx-auto px-4 py-8\">\n");
      out.write("        <div class=\"max-w-6xl mx-auto\">\n");
      out.write("            <div class=\"text-center mb-8\">\n");
      out.write("                <h1 class=\"text-3xl font-bold text-black mb-2\">Complete Your Enrollment</h1>\n");
      out.write("                <p class=\"text-gray-600\">Review your order and select payment method</p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"grid grid-cols-1 lg:grid-cols-2 gap-8\">\n");
      out.write("                <!-- Left Column: Bill Details -->\n");
      out.write("                <div class=\"bg-white rounded-xl payment-card p-6\">\n");
      out.write("                    <h2 class=\"text-2xl font-bold text-black mb-6 pb-4 border-b border-gray-200\">\n");
      out.write("                        <i class=\"fas fa-receipt mr-2 text-orange-500\"></i>\n");
      out.write("                        Invoice Details\n");
      out.write("                    </h2>\n");
      out.write("                    \n");
      out.write("                    <!-- Student Info -->\n");
      out.write("                    <div class=\"mb-6\">\n");
      out.write("                        <h3 class=\"text-lg font-semibold text-black mb-3\">Student Information</h3>\n");
      out.write("                        <div class=\"bg-gray-50 p-4 rounded-lg\">\n");
      out.write("                            <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">\n");
      out.write("                                <div>\n");
      out.write("                                    <p class=\"text-sm text-gray-500\">Name</p>\n");
      out.write("                                    <p class=\"font-medium text-black\">");
      out.print( s.getName() );
      out.write("</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div>\n");
      out.write("                                    <p class=\"text-sm text-gray-500\">Email</p>\n");
      out.write("                                    <p class=\"font-medium text-black\">");
      out.print( s.getMail() );
      out.write("</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div>\n");
      out.write("                                    <p class=\"text-sm text-gray-500\">Date</p>\n");
      out.write("                                    <p class=\"font-medium text-black\">");
      out.print( LocalDateTime.now());
      out.write("</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <!-- Course Info -->\n");
      out.write("                    <div class=\"mb-6\">\n");
      out.write("                        <h3 class=\"text-lg font-semibold text-black mb-3\">Course Details</h3>\n");
      out.write("                        <div class=\"border border-gray-200 rounded-lg overflow-hidden\">\n");
      out.write("                            <div class=\"p-4 border-b border-gray-200\">\n");
      out.write("                                <div class=\"flex justify-between items-start\">\n");
      out.write("                                    <div>\n");
      out.write("                                        <h4 class=\"font-bold text-lg text-black\">");
      out.print( c.getCourseName() );
      out.write("</h4>\n");
      out.write("                                        <p class=\"text-gray-600 text-sm mt-1\">");
      out.print( c.getCourseInfo());
      out.write("</p>\n");
      out.write("                                        <div class=\"flex items-center mt-2\">\n");
      out.write("                                            <span class=\"bg-gray-100 text-gray-800 text-xs px-3 py-1 rounded-full mr-2\">\n");
      out.write("                                                <i class=\"fas fa-clock mr-1\"></i>");
      out.print( c.getMonths());
      out.write(" months\n");
      out.write("                                            </span>\n");
      out.write("                                            \n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"text-right\">\n");
      out.write("                                        <div class=\"text-2xl font-bold text-black\">&#8377;");
      out.print(c.getFees());
      out.write("0/-</div>\n");
      out.write("                                        <div class=\"text-sm text-gray-500\">Course Fee</div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <!-- Bill Summary -->\n");
      out.write("                    <div>\n");
      out.write("                        <h3 class=\"text-lg font-semibold text-black mb-3\">Bill Summary</h3>\n");
      out.write("                        <div class=\"bg-gray-50 p-4 rounded-lg\">\n");
      out.write("                            <div class=\"space-y-3\">\n");
      out.write("                                <div class=\"flex justify-between\">\n");
      out.write("                                    <span class=\"text-gray-600\">Course Fee</span>\n");
      out.write("                                    <span class=\"font-medium\">&#8377;");
      out.print(courseFees);
      out.write("0</span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"flex justify-between\">\n");
      out.write("                                    <span class=\"text-gray-600\">GST (18%)</span>\n");
      out.write("                                    <span class=\"font-medium\">&#8377;");
      out.print(tax);
      out.write("0</span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"border-t border-gray-300 pt-3 mt-3\">\n");
      out.write("                                    <div class=\"flex justify-between\">\n");
      out.write("                                        <span class=\"text-lg font-bold text-black\">Total Amount</span>\n");
      out.write("                                        <span class=\"text-2xl font-bold text-black\">&#8377;");
      out.print(totalAmount);
      out.write("</span>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("               \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Right Column: Payment Method -->\n");
      out.write("                <div class=\"bg-white rounded-xl payment-card p-6\">\n");
      out.write("                    <h2 class=\"text-2xl font-bold text-black mb-6 pb-4 border-b border-gray-200\">\n");
      out.write("                        <i class=\"fas fa-credit-card mr-2 text-orange-500\"></i>\n");
      out.write("                        Select Payment Method\n");
      out.write("                    </h2>\n");
      out.write("                    \n");
      out.write("                    <!-- Payment Form -->\n");
      out.write("                    <form action=\"payment\" method=\"POST\" class=\"space-y-6\">\n");
      out.write("                        <!-- Hidden fields -->\n");
      out.write("                        <input type=\"hidden\" name=\"courseId\" value=\"");
      out.print(courseId );
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"totalAmount\" value=\"");
      out.print( totalAmount );
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"studentId\" value=\"");
      out.print( s.getId() );
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"tax\" value=\"");
      out.print(tax);
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"fees\" value=\"");
      out.print(courseFees);
      out.write("\">\n");
      out.write("                        \n");
      out.write("                        <!-- Payment Options -->\n");
      out.write("                        <div class=\"space-y-4\">\n");
      out.write("                            <!-- Credit/Debit Card -->\n");
      out.write("                            <div>\n");
      out.write("                                <input type=\"radio\" id=\"card\" name=\"paymentMethod\" value=\"card\" class=\"payment-method hidden\" required>\n");
      out.write("                                <label for=\"card\" class=\"payment-option block p-4 border rounded-lg cursor-pointer\">\n");
      out.write("                                    <div class=\"flex items-center\">\n");
      out.write("                                        <div class=\"bg-blue-50 p-3 rounded-lg mr-4\">\n");
      out.write("                                            <i class=\"fas fa-credit-card text-blue-500 text-xl\"></i>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"flex-grow\">\n");
      out.write("                                            <h3 class=\"font-bold text-black\">Credit/Debit Card</h3>\n");
      out.write("                                            <p class=\"text-sm text-gray-600\">Pay using Visa, MasterCard, or Rupay</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"text-green-500\">\n");
      out.write("                                            <i class=\"fas fa-check-circle\"></i>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </label>\n");
      out.write("                                \n");
      out.write("                                <!-- Card Details (Shown when selected) -->\n");
      out.write("                                <div class=\"mt-4 ml-12 p-4 bg-gray-50 rounded-lg space-y-4 hidden\" id=\"card-details\">\n");
      out.write("                                    <div>\n");
      out.write("                                        <label class=\"block text-sm font-medium text-gray-700 mb-2\">Card Number</label>\n");
      out.write("                                        <input type=\"text\" name=\"cardNumber\" placeholder=\"1234 5678 9012 3456\" \n");
      out.write("                                               pattern=\"[0-9\\s]{13,19}\" maxlength=\"19\"\n");
      out.write("                                               class=\"w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"grid grid-cols-2 gap-4\">\n");
      out.write("                                        <div>\n");
      out.write("                                            <label class=\"block text-sm font-medium text-gray-700 mb-2\">Expiry Date</label>\n");
      out.write("                                            <input type=\"text\" name=\"expiryDate\" placeholder=\"MM/YY\" \n");
      out.write("                                                   pattern=\"(0[1-9]|1[0-2])\\/[0-9]{2}\"\n");
      out.write("                                                   class=\"w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500\">\n");
      out.write("                                        </div>\n");
      out.write("                                        <div>\n");
      out.write("                                            <label class=\"block text-sm font-medium text-gray-700 mb-2\">CVV</label>\n");
      out.write("                                            <input type=\"password\" name=\"cvv\" placeholder=\"123\" \n");
      out.write("                                                   pattern=\"[0-9]{3,4}\" maxlength=\"4\"\n");
      out.write("                                                   class=\"w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500\">\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                            <!-- UPI -->\n");
      out.write("                            <div>\n");
      out.write("                                <input type=\"radio\" id=\"upi\" name=\"paymentMethod\" value=\"upi\" class=\"payment-method hidden\">\n");
      out.write("                                <label for=\"upi\" class=\"payment-option block p-4 border rounded-lg cursor-pointer\">\n");
      out.write("                                    <div class=\"flex items-center\">\n");
      out.write("                                        <div class=\"bg-purple-50 p-3 rounded-lg mr-4\">\n");
      out.write("                                            <i class=\"fas fa-mobile-alt text-purple-500 text-xl\"></i>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"flex-grow\">\n");
      out.write("                                            <h3 class=\"font-bold text-black\">UPI Payment</h3>\n");
      out.write("                                            <p class=\"text-sm text-gray-600\">Pay using Google Pay, PhonePe, Paytm</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </label>\n");
      out.write("                                \n");
      out.write("                                <!-- UPI ID (Shown when selected) -->\n");
      out.write("                                <div class=\"mt-4 ml-12 p-4 bg-gray-50 rounded-lg space-y-4 hidden\" id=\"upi-details\">\n");
      out.write("                                    <div>\n");
      out.write("                                        <label class=\"block text-sm font-medium text-gray-700 mb-2\">UPI ID</label>\n");
      out.write("                                        <input type=\"text\" name=\"upiId\" placeholder=\"username@bank\" \n");
      out.write("                                               class=\"w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                            <!-- Net Banking -->\n");
      out.write("                            <div>\n");
      out.write("                                <input type=\"radio\" id=\"netbanking\" name=\"paymentMethod\" value=\"netbanking\" class=\"payment-method hidden\">\n");
      out.write("                                <label for=\"netbanking\" class=\"payment-option block p-4 border rounded-lg cursor-pointer\">\n");
      out.write("                                    <div class=\"flex items-center\">\n");
      out.write("                                        <div class=\"bg-green-50 p-3 rounded-lg mr-4\">\n");
      out.write("                                            <i class=\"fas fa-university text-green-500 text-xl\"></i>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"flex-grow\">\n");
      out.write("                                            <h3 class=\"font-bold text-black\">Net Banking</h3>\n");
      out.write("                                            <p class=\"text-sm text-gray-600\">Pay directly from your bank account</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </label>\n");
      out.write("                                \n");
      out.write("                                <!-- Bank Selection (Shown when selected) -->\n");
      out.write("                                <div class=\"mt-4 ml-12 p-4 bg-gray-50 rounded-lg space-y-4 hidden\" id=\"netbanking-details\">\n");
      out.write("                                    <div>\n");
      out.write("                                        <label class=\"block text-sm font-medium text-gray-700 mb-2\">Select Bank</label>\n");
      out.write("                                        <select name=\"bank\" class=\"w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500\">\n");
      out.write("                                            <option value=\"\">Choose your bank</option>\n");
      out.write("                                            <option value=\"sbi\">State Bank of India</option>\n");
      out.write("                                            <option value=\"hdfc\">HDFC Bank</option>\n");
      out.write("                                            <option value=\"icici\">ICICI Bank</option>\n");
      out.write("                                            <option value=\"axis\">Axis Bank</option>\n");
      out.write("                                            <option value=\"kotak\">Kotak Mahindra Bank</option>\n");
      out.write("                                            <option value=\"pnb\">Punjab National Bank</option>\n");
      out.write("                                        </select>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                            <!-- Wallet -->\n");
      out.write("                            <div>\n");
      out.write("                                <input type=\"radio\" id=\"wallet\" name=\"paymentMethod\" value=\"wallet\" class=\"payment-method hidden\">\n");
      out.write("                                <label for=\"wallet\" class=\"payment-option block p-4 border rounded-lg cursor-pointer\">\n");
      out.write("                                    <div class=\"flex items-center\">\n");
      out.write("                                        <div class=\"bg-yellow-50 p-3 rounded-lg mr-4\">\n");
      out.write("                                            <i class=\"fas fa-wallet text-yellow-500 text-xl\"></i>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"flex-grow\">\n");
      out.write("                                            <h3 class=\"font-bold text-black\">Digital Wallet</h3>\n");
      out.write("                                            <p class=\"text-sm text-gray-600\">Pay using Paytm Wallet, Amazon Pay</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </label>\n");
      out.write("                                \n");
      out.write("                                <!-- Wallet Selection (Shown when selected) -->\n");
      out.write("                                <div class=\"mt-4 ml-12 p-4 bg-gray-50 rounded-lg space-y-4 hidden\" id=\"wallet-details\">\n");
      out.write("                                    <div>\n");
      out.write("                                        <label class=\"block text-sm font-medium text-gray-700 mb-2\">Select Wallet</label>\n");
      out.write("                                        <select name=\"walletType\" class=\"w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500\">\n");
      out.write("                                            <option value=\"\">Choose your wallet</option>\n");
      out.write("                                            <option value=\"paytm\">Paytm Wallet</option>\n");
      out.write("                                            <option value=\"amazonpay\">Amazon Pay</option>\n");
      out.write("                                            <option value=\"phonepe\">PhonePe Wallet</option>\n");
      out.write("                                            <option value=\"mobikwik\">MobiKwik</option>\n");
      out.write("                                        </select>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <!-- Terms and Conditions -->\n");
      out.write("                        <div class=\"flex items-start\">\n");
      out.write("                            <div class=\"flex items-center h-5\">\n");
      out.write("                                <input type=\"checkbox\" id=\"terms\" name=\"terms\" required\n");
      out.write("                                       class=\"h-4 w-4 text-orange-500 focus:ring-orange-400 border-gray-300 rounded\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"ml-3\">\n");
      out.write("                                <label for=\"terms\" class=\"text-sm text-gray-700\">\n");
      out.write("                                    I agree to the \n");
      out.write("                                    <a href=\"terms.jsp\" class=\"link-orange font-medium\">Terms of Service</a> \n");
      out.write("                                    and authorize ProDhee to charge my selected payment method for the total amount shown.\n");
      out.write("                                </label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <!-- Payment Buttons -->\n");
      out.write("                        <div class=\"flex space-x-4 pt-4\">\n");
      out.write("                            <button type=\"submit\" \n");
      out.write("                                    class=\"flex-1 btn-primary font-semibold py-4 rounded-lg text-lg hover:shadow-lg transition duration-300\">\n");
      out.write("                                <i class=\"fas fa-lock mr-2\"></i>\n");
      out.write("                                Pay &#8377;");
      out.print(totalAmount);
      out.write("0/-\n");
      out.write("                            </button>\n");
      out.write("                            <a href=\"courses/category=all\" \n");
      out.write("                               class=\"flex-1 btn-outline font-semibold py-4 rounded-lg text-lg text-center hover:shadow-lg transition duration-300\">\n");
      out.write("                                Cancel Payment\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <!-- Security Note -->\n");
      out.write("                        <div class=\"mt-6 p-4 bg-blue-50 rounded-lg\">\n");
      out.write("                            <div class=\"flex items-center\">\n");
      out.write("                                <i class=\"fas fa-shield-alt text-blue-500 mr-3\"></i>\n");
      out.write("                                <div>\n");
      out.write("                                    <p class=\"text-sm text-blue-700 font-medium\">Secure Payment</p>\n");
      out.write("                                    <p class=\"text-xs text-blue-600\">Your payment information is encrypted and secure</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </main>\n");
      out.write("    \n");
      out.write("    <!-- Footer -->\n");
      out.write("    ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style>\n");
      out.write("        /* Sunset Orange Color Palette */\n");
      out.write("        :root {\n");
      out.write("            --sunset-orange: #FF6B35;\n");
      out.write("            --sunset-orange-light: #FF8E5E;\n");
      out.write("            --sunset-orange-dark: #E55A2B;\n");
      out.write("            --black: #000000;\n");
      out.write("            --white: #FFFFFF;\n");
      out.write("            --gray-light: #F5F5F5;\n");
      out.write("            --gray-medium: #E0E0E0;\n");
      out.write("            --gray-dark: #333333;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .course-card {\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("            border: 1px solid var(--gray-medium);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .course-card:hover {\n");
      out.write("            transform: translateY(-8px);\n");
      out.write("            box-shadow: 0 12px 20px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-link {\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-link.active::after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            bottom: -5px;\n");
      out.write("            left: 0;\n");
      out.write("            right: 0;\n");
      out.write("            height: 3px;\n");
      out.write("            background-color: var(--sunset-orange);\n");
      out.write("            border-radius: 3px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .hero-gradient {\n");
      out.write("            background: linear-gradient(135deg, #FF6B35 0%, #FF8E5E 50%, #FFB38A 100%);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-primary {\n");
      out.write("            background-color: var(--sunset-orange);\n");
      out.write("            color: var(--white);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background-color: var(--sunset-orange-dark);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-outline {\n");
      out.write("            border: 2px solid var(--sunset-orange);\n");
      out.write("            color: var(--sunset-orange);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn-outline:hover {\n");
      out.write("            background-color: var(--sunset-orange);\n");
      out.write("            color: var(--white);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .category-tag {\n");
      out.write("            font-weight: 600;\n");
      out.write("            padding: 4px 12px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            font-size: 0.75rem;\n");
      out.write("            display: inline-block;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("       \n");
      out.write("        \n");
      out.write("        .category-courseName {\n");
      out.write("            background-color: rgba(0, 150, 136, 0.15);\n");
      out.write("            color: #009688;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("     \n");
      out.write("        .level-category {\n");
      out.write("            background-color: rgba(255, 152, 0, 0.15);\n");
      out.write("            color: #FF9800;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("       \n");
      out.write("        \n");
      out.write("        /* Mobile menu animation */\n");
      out.write("        @keyframes slideDown {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateY(-10px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateY(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .mobile-menu {\n");
      out.write("            animation: slideDown 0.3s ease-out;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Course filtering with CSS */\n");
      out.write("        .course-filter:target ~ #courses-container .course-card {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #filter-all:target ~ #courses-container .course-card,\n");
      out.write("        #filter-java:target ~ #courses-container .course-card[data-category=\"java\"],\n");
      out.write("        #filter-python:target ~ #courses-container .course-card[data-category=\"python\"],\n");
      out.write("        #filter-mern:target ~ #courses-container .course-card[data-category=\"mern\"],\n");
      out.write("        #filter-devops:target ~ #courses-container .course-card[data-category=\"devops\"] {\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	 <!-- Footer -->\n");
      out.write("    <footer class=\"bg-black text-white pt-10 pb-6\">\n");
      out.write("        <div class=\"container mx-auto px-4\">\n");
      out.write("            <div class=\"grid grid-cols-1 md:grid-cols-4 gap-8 mb-8\">\n");
      out.write("                <div>\n");
      out.write("                    <div class=\"flex items-center space-x-3 mb-4\">\n");
      out.write("                        <div class=\"bg-white text-black p-2 rounded-lg\">\n");
      out.write("                            <i class=\"fas fa-graduation-cap text-2xl\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <h2 class=\"text-xl font-bold\">ProDhee</h2>\n");
      out.write("                            <p class=\"text-sm text-gray-400\">Student Courses Portal</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <p class=\"text-gray-400\">Empowering students with industry-relevant skills through expert-led courses in modern technologies.</p>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div>\n");
      out.write("                    <h3 class=\"text-lg font-bold mb-4 text-white\">Quick Links</h3>\n");
      out.write("                    <ul class=\"space-y-2\">\n");
      out.write("                        <li><a href=\"#filter-all\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">Home</a></li>\n");
      out.write("                        <li><a href=\"#filter-all\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">All Courses</a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">Student Dashboard</a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">Instructors</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div>\n");
      out.write("                    <h3 class=\"text-lg font-bold mb-4 text-white\">Course Categories</h3>\n");
      out.write("                    <ul class=\"space-y-2\">\n");
      out.write("                        <li><a href=\"courses?category=Java\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">Java Programming</a></li>\n");
      out.write("                        <li><a href=\"courses?category=Python\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">Python & Data Science</a></li>\n");
      out.write("                        <li><a href=\"courses?category=Angular%2FReact\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">MEAN and MERN Stacks</a></li>\n");
      out.write("                        <li><a href=\"courses?category=Cloud\" class=\"text-gray-400 hover:text-orange-400 transition duration-200\">DevOps & Cloud</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div>\n");
      out.write("                    <h3 class=\"text-lg font-bold mb-4 text-white\">Contact Us</h3>\n");
      out.write("                    <ul class=\"space-y-3\">\n");
      out.write("                        <li class=\"flex items-center space-x-3 text-gray-400\">\n");
      out.write("                            <i class=\"fas fa-envelope text-orange-500\"></i>\n");
      out.write("                            <span>support@prodheetech.com</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"flex items-center space-x-3 text-gray-400\">\n");
      out.write("                            <i class=\"fas fa-phone text-orange-500\"></i>\n");
      out.write("                            <span>+91 9900990099</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"flex items-center space-x-3 text-gray-400\">\n");
      out.write("                            <i class=\"fas fa-map-marker-alt text-orange-500\"></i>\n");
      out.write("                            <span>Yelahanka, Bangalore 560001</span>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"border-t border-gray-800 pt-6 flex flex-col md:flex-row justify-between items-center\">\n");
      out.write("                <p class=\"text-gray-400 text-sm mb-4 md:mb-0\">&copy; 2025 ProDhee. All rights reserved.</p>\n");
      out.write("                <div class=\"flex space-x-4\">\n");
      out.write("                    <a href=\"#\" class=\"text-gray-400 hover:text-orange-500 transition duration-200\">\n");
      out.write("                        <i class=\"fab fa-facebook-f text-xl\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"#\" class=\"text-gray-400 hover:text-orange-500 transition duration-200\">\n");
      out.write("                        <i class=\"fab fa-twitter text-xl\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"#\" class=\"text-gray-400 hover:text-orange-500 transition duration-200\">\n");
      out.write("                        <i class=\"fab fa-linkedin-in text-xl\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"#\" class=\"text-gray-400 hover:text-orange-500 transition duration-200\">\n");
      out.write("                        <i class=\"fab fa-instagram text-xl\"></i>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- CSS-only Payment Method Toggle -->\n");
      out.write("    <style>\n");
      out.write("        /* Show payment details when payment method is selected */\n");
      out.write("        #card:checked ~ label[for=\"card\"] + #card-details,\n");
      out.write("        #upi:checked ~ label[for=\"upi\"] + #upi-details,\n");
      out.write("        #netbanking:checked ~ label[for=\"netbanking\"] + #netbanking-details,\n");
      out.write("        #wallet:checked ~ label[for=\"wallet\"] + #wallet-details {\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Hide payment details by default */\n");
      out.write("        #card-details,\n");
      out.write("        #upi-details,\n");
      out.write("        #netbanking-details,\n");
      out.write("        #wallet-details {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
